
// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using PlatzDemo.SchemaStore;

namespace PlatzDemo.SchemaStore
{
    #region Interface 

    public partial interface IPlatzDemoService
    {
        List<OrderItemProduct> GetOrderItemProductList(params object[] parameters);
    }

    #endregion

    #region Data Service 

    public partial class PlatzDemoService : StoreDataServiceBase<PlatzDemoDataContext>, IPlatzDemoService
    {
        public List<OrderItemProduct> GetOrderItemProductList(params object[] parameters)
        {
            var sql = @$"
SELECT
      o.Id AS Id
    , o.OrderId AS OrderId
    , o.ProductId AS ProductId
    , TRY_CAST(JSON_VALUE(o.data, '$.Qty') AS INT) AS Qty
    , JSON_VALUE(p.data, '$.Name') AS Name
    , TRY_CAST(JSON_VALUE(p.data, '$.Price') AS MONEY) AS Price
FROM [PlatzDemo].[Product] p
INNER JOIN [PlatzDemo].[OrderItem] o ON p.Id = o.ProductId
WHERE o.OrderId = @p1
";
            using var db = GetDbContext();
            var result = db.ExecuteQuery<OrderItemProduct>(sql, parameters);
            return result;
        }

    }

    #endregion

    #region Entities

    public partial class OrderItemProduct
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }

    #endregion
}
